package com.acme;

import com.acme.servermgr.ServerManager;
import com.acme.statusmgr.StatusController;
import com.acme.statusmgr.beans.ServerStatus;
import jdk.net.SocketFlow;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);


    }

}
